### ISSUE TITLE
[TASK] Rotate signers if signing unsigned proposals fails

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#154]
# Overview
Right now I don't think we have a fallback method for re-signing unsigned proposals when the signing process fails. For this task we should investigate and implement a rotation of signers and re-signing of the unsigned proposals that have failed in order.
- [ ] Identify the signers that have not participated in signing
- [ ] Rotate the signing set to remove and replace the signers that were absent or behaving maliciously (including being offline)
- [ ] Re-sign proposals that failed to be signed
- [ ] Test

**Comment by drewstone** [comment]
### Thoughts from meeting w/ Shady
If the signing fails due to misbehavior then we should see the party indices that misbehaved. We should
- Identify a deterministic way to select new signers with new parties excluding the misbehaved set (assuming everyone receives the same set)
- Re-run signing.
