### ISSUE TITLE
[SPEC] Match proposal data on chain type and decode accordingly

### ISSUE THREAD

**Issue by saiakilesh** [webb-tools/dkg-substrate#160]
## Overview
Right now we use the same `decode` functions for each type of chain. But this is an issue since, for example, `decode_token_add_proposal` is EVM specific: https://github.com/webb-tools/dkg-substrate/blob/master/pallets/dkg-proposal-handler/src/lib.rs#L908

We can fix this in the following way: 
1. Parse the proposal header first
2. Extract the chain type
3. Match on each chain type and call the appropriate validation function

## Code
Let's take an example of how we will change the flow for the `TokenAdd` proposal.

The new `decode_token_add_proposal` function will look like:

```
fn decode_token_add_proposal(data: &[u8]) -> Result<ProposalHeader<T::ChainId>, Error<T>> {
    let header = Self::decode_proposal_header(data)?;
    if let Ok((chain_id, _)) = header.map(Into::into) {
        let chain_type = get_chain_type_from_chain_id(chain_id); // not sure if a function like this already exists
        match chain_type {
            [1, 0] => {
                // Validate data for EVM chain
                if data.len() != 60 {
                    return Err(Error::<T>::ProposalFormatInvalid)?
                }
                let mut new_token_address_bytes = [0u8; 20];
                new_token_address_bytes.copy_from_slice(&data[40..60]);
                let new_token_address = Address::from(new_token_address_bytes);
            },
            [2, 0] => {
                // Validate data for Substrate chain
                ...
            },
            ...
            ,
            _ => panic!("Invalid chain id type"),
        }
    }
    Ok(header)
}
```

**Comment by drewstone** [comment]
Looks good, we can get started on an implementation 👍 .

I would also change the `to_bytes` function on the ChainIdType` to `get_type_bytes`.
