### ISSUE TITLE
[SPEC] Document and revise refresh process with key resharing focus

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#240]
# Overview

- Have more consistent key rotation process in the dkg
- Specifically, the active authorities should generate their keys before the queued authorities in all cases

**Comment by drewstone** [comment]
@dutterbutter @saiakilesh we should:
- Document the current process more thoroughly (i.e. we run keygen twice at genesis and every new session check whether to run again for both sets of authorities). We should analyze the functions more closely and actually add thorough documentation here.

Then we should identify how to clean it up a bit. I think it could be improved by:
- Starting the genesis keygen first without the next keygen. Potentially, we set the genesis set and first next authority keygen to be this first genesis keygen.
- Then in every session that is not the genesis setting, we start keygen for these new queued/next authorities.
- We should document/spec the process that this update will lead to and start implementation once we understand and agree on the ordering of operations.
