### ISSUE TITLE
[TASK] Check if public key is `None`

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#275]
**Task summary**

- Need to ensure public key is `None` in [`dkg-metadata pallet`](https://github.com/webb-tools/dkg-substrate/blob/adcfa78a9691f57407e96941b7381bfbf3f33326/pallets/dkg-metadata/src/lib.rs#L1020)

**Comment by Doordashcon** [comment]
Hello @dutterbutter, want to attempt this issue, I suppose a test case will be needed as well?

**Comment by drewstone** [comment]
I believe this is already handled @Doordashcon [here](https://github.com/webb-tools/dkg-substrate/blob/master/pallets/dkg-metadata/src/lib.rs#L662). Would be interested to have you look around other issues and see if you can tackle them!
