### ISSUE TITLE
[BUG] Investigate high bandwidth usage of DKG

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#294]
**Describe the bug**

Currently the standalone testnet is utilizing ~`Avg: 105.59 MBit/s`. This is far above expectation is has iteratively grown in size each day. 

**Screenshots**

<img width="1181" alt="Screen Shot 2022-04-20 at 5 31 28 PM" src="https://user-images.githubusercontent.com/29983536/164268880-e75a53d7-9781-45b9-8346-c66db906d1eb.png">

**Expected behaviour**

The DKG should not be utilizing this much bandwidth after only a week in operation.

**Comment by dutterbutter** [comment]
Investigation tasks:

- [ ] Add DKG metrics for messages that can be captured by Prometheus
- [ ] Log messages to understand how many messages are sent / received through a counter

**Comment by drewstone** [comment]
Yep I believe Thomas is working on this.

**Comment by dutterbutter** [comment]
Relevant PR: https://github.com/webb-tools/dkg-substrate/pull/302
