### ISSUE TITLE
[SPEC] Utilise P2P messages over broadcast when possible.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#300]
# Overview 

We use gossip for all outbound messages. Sometimes this is unnecessary, since some messages just need to be delivered directly to a known recipient. We should leverage whether we need to broadcast messages to all peers or just to a specific peer to reduce our outbound networking traffic (and inbound).

## Examples 

# Questions/Issues

**Comment by dutterbutter** [comment]
Closed in #304
