### ISSUE TITLE
[TASK] Re-enable pallet logging

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#310]
**Task summary**

We currently do not have visible logs for our pallets. We need to add back logging in these pallets and add documentation in the readme outlining how to do so.

- [ ] Re-enable pallet level logging
- [ ] Document the process and add instructions to readme

**Comment by 1xstj** [comment]
Based on testing, most pallet logs are working with the exception of https://github.com/webb-tools/dkg-substrate/blob/async/pallets/dkg-metadata/src/lib.rs#L234-L262 and other std scoped logs. The issue seems to be the std logs.
