### ISSUE TITLE
[TASK] Test start and stopping nodes and ensure correct behaviour

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#324]
**Task summary**
If I start and stop a node that is not in the middle of signing or keygen, I should expect the node to continue to work and not cause issues. If there are issues with this, we should identify them in this task and solve them.

**Checklist**
- [x] Run 3 nodes, let keygen finish, stop one node and start it back up.
- [x] Run 3 nodes, let keygen finish, stop all nodes and start all back up.

**Comment by shekohex** [comment]
Closed by #332
