### ISSUE TITLE
[TASK] E2E Testing for different DKG flows

### ISSUE THREAD

**Issue by shekohex** [webb-tools/dkg-substrate#336]
**Task summary**

In this task we want to cover and write an end to end testing for the following DKG flows, especially the one we already covered in #332  

**Specification reference**

We need to cover tests for the following scenarios:

- Start `3` DKG Nodes with the `KeygenThreshold` initially set to `2`, then update the `KeygenThreshold` to `3`; we expect the `KeygenThreshold` to change and the `BestAuthorities` should be equal to `3` Nodes after the next session.
- Following the above test case, change the `KeygenThreshold` back to `2`, after the next session we expect that `BestAuthorities` are now just `2`.
- Start `3` DKG Nodes with the `KeygenThreshold` initially set to `2`, then update the `KeygenThreshold` to `3`; after the next session, and the `BestAuthorities` are `3`, shutdown one of these nodes and expect a misbehaviour report happens on chain, then in the next session you should expect the `BestAuthorities` are `2`.
- Following the above test case, start back the stopped node, unjail it, then update the `KeygenThreshold` to `3`; we expect after the next session that `BestAuthorities` are now back to `3` and the DKG continues to rotate and update.

**Other information and links**

Read more in this PR #332

**Comment by dutterbutter** [comment]
Closed in #332
