### ISSUE TITLE
[TASK] Add logs to investigate on-chain key publish failure

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#344]
**Issue summary**
Keygen fails to get on-chain but looks to finish off-chain.

**Add logs**
- https://github.com/webb-tools/dkg-substrate/blob/master/dkg-gadget/src/storage/public_keys.rs#L78
- https://github.com/webb-tools/dkg-substrate/blob/master/pallets/dkg-metadata/src/lib.rs#L1392 (use the pallet name)
- Try to differentiate between genesis/queued a bit more explicitly (might just be helpful at launch)

**Comment by dutterbutter** [comment]
Closed in #345
