### ISSUE TITLE
[TASK] Consider splitting gossip protocol types between keygen/signing

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#363]
**Issue summary**
We currently process all incoming DKG messages within the same stream and flow, which could pose issues if there are ever issues on the networking layer. Instead, we can consider separating between keygen messages and signing messages. We would then have 2 streams for each of the protocols.

We would need to:
1. Create different protocol names for the keygen and sign sub-protocols.
2. Share the same networking code.
3. Handle incoming messages separately in new handlers `process_incoming_keygen_msg` and `process_incoming_sign_msg`.
4. Gossip outgoing messages separately using protocol specific `keygen_gossip_handler` and `sign_gossip_handler`.

**Other information and links**
- https://github.com/paritytech/substrate/blob/master/client/network/src/transactions.rs

**Comment by shekohex** [comment]
Closed in #365
