### ISSUE TITLE
[TASK] Consider splitting DKGMessage to keygen/sign types

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#367]
**Task summary**
After #365 we are using separate gossip streams to process keygen/sign messages. But the `DKGMsgPayload` is still shared among all message types. Separating the message types makes clear distinction between the messages, we can process each type differently and support custom requirement.

**Other information and links**
https://github.com/webb-tools/dkg-substrate/blob/ec56e3649cf3f546eca2d7eec608198871135396/dkg-primitives/src/types.rs#L101

**Comment by drewstone** [comment]
I support this. It is worth taking into account that there are two messages here that deal with non-DKG protocols (public key gossip and misbehaviour). Do you have a small writeup of potential new names you think would serve the 3 types of messages we have? (Keygen / Sign / GeneralGossip)?

**Comment by shekohex** [comment]
Closed in #365
