### ISSUE TITLE
[TASK] Submitting a batch of signed proposals per block

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#37]
# Overview
We want to submit a batch of signed proposals if there are more than 1. We do however want to ensure that this submission is properly weighted.

```
// choose weight dependent on `props.len()`
pub fn submit_signed_proposal(
  origin: OriginFor<T>,
  props: Vec<ProposalType>,
) -> DispatchResultWithPostInfo {
```

# Checklist
- [x] Implement batched submissions
- [x] Implement benchmarking that is dependent on the # of submissions.

**Comment by Wizdave97** [comment]
Done
