### ISSUE TITLE
[BUG]  Authorities reputation map key don't encode the authority id or the authority account 32  correclty

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/dkg-substrate#398]
**Describe the bug**

**To Reproduce**
1. Run the archive standalone node  `$ ./scripts/run-archive-local-net.sh`
2. Go to Substrate portal
3. Query the authority's map
4. Query the authority's reputation map
5. Reputation map doesn't use the same key

**Expected behavior**
We should be able to get reputation by account 32

**Screenshots**
![image](https://user-images.githubusercontent.com/35463181/192773248-b2f0f153-a5ed-4b29-9db9-b759192aa06b.png)

**Other information and links**

**Comment by drewstone** [comment]
I think this conversion is bad and should be double-checked:
https://github.com/webb-tools/dkg-substrate/blob/master/pallets/dkg-metadata/src/lib.rs#L1221

**Comment by drewstone** [comment]
It is possible we just need to change the return value of this function: https://github.com/webb-tools/dkg-substrate/blob/7d0589f20fd08f7898f951eaae483c3fa70c69e1/dkg-runtime-primitives/src/utils.rs#L52-L73
```
pub fn verify_signer_from_set_ecdsa(
	maybe_signers: Vec<ecdsa::Public>,
	msg: &[u8],
	signature: &[u8],
) -> (Option<ecdsa::Public>, bool) {
	let mut signer = None;
	let res = maybe_signers.iter().any(|x| {
		if let Ok(data) = recover_ecdsa_pub_key(msg, signature) {
			let recovered = &data[..32];
			if x.0[1..].to_vec() == recovered.to_vec() {
				signer = Some(*x.0);
				true
			} else {
				false
			}
		} else {
			false
		}
	});

	(signer, res)
}
```

**Comment by AhmedKorim** [comment]
A similar issue may accountToAuthority for 

```js
const authoritesAccounts = await api.query.dkg.accountToAuthority.entries();
const Keys = authoritesAccounts.map(([key, val]) => {
  return {
    accountId: key.args[0],
    authorityId: val,
  };
});
console.log(JSON.stringify(Keys, null, 2));
```
The console.log output for this  is
```json
[
  {
    "accountId": "0x69a1e29c03787e72adbd6fc93195376051d974bb545b2a5f42d834e0a0adfb83",
    "authorityId": "0x036aec5853fba2662f31ba89e859ac100daa6c58dc8fdaf0555565663f2b99f8f2"
  },
  {
    "accountId": "0xce82c1e3b079d6c9d25bb5fb7f59a8a93123e4e12f54c6dbcdef4ed12a9fede5",
    "authorityId": "0x028a4c0781f8369fdd873f8531491f24e2e806fd11a13d828cb4099e6c1045103e"
  },
  {
    "accountId": "0xd6f1157ab0717d3465e8fa56e51254f7ee629e5c601ce01e470e8ae6f8731c87",
    "authorityId": "0x02427a6cf7f1d7538d9e3e4df834e27db337fd6ef0f530aab4e9799ff865e843fc"
  }
]
```
and be encoding the account id to ss58 format say using `import { encodeAddress } from '@polkadot/util-crypto';` `0x69a1e29c03787e72adbd6fc93195376051d974bb545b2a5f42d834e0a0adfb83` The output is `5ETCyWAB5g1HWCMwMcJRswsqj2idbYowXRojNRUUUmXZT1A6` and this isn't an authority account

**Comment by AhmedKorim** [comment]
```js
const authorityReputations = await api.query.dkg.authorityReputations.entries()

const authorityReputations = authorityReputations.map(([key,val]) => {
return {
accountId: key.args[0],
authorityId:val.toNumber()
}
})
console.log(JSON.stringify(Keys,null,2))
```
The console.log output for this is
```
[
  {
    "accountId": "0x4bec6d7454c05d719844aa1dd8b0d3c35f40f7cf5e56d99f5ef2f702d80d942d",
    "authorityId": 1000000000
  },
  {
    "accountId": "0xcfc43f79201172a842ac35cb6f3ca2b6103e352e2bfada243ec477a6dd5d7826",
    "authorityId": 1000000000
  }
]
```

**Comment by 1xstj** [comment]
Issue with polkadotjs encoding : https://github.com/polkadot-js/api/issues/5247
