### ISSUE TITLE
Keygen timeout before session 10

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#402]
**Describe the bug**

The arana-alpha standalone network which contains three nodes has stopped generating a dkg public key after session 9. The three nodes are still finalizing blocks and progressing the chain but keygen has stalled at session 10. We are currently running t=2 (signing threshold) n=3  (keygen threshold).

**To Reproduce**
Steps to reproduce the observe behaviour:
1. Go to [polkadot UI](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Farana-alpha-1.webb.tools#/chainstate) > Developer > ChainState > DKG > dkgPublickey()

**You will notice:**
```
dkg.dkgPublicKey: (u64,Bytes)
[
  9
  0x0333eac660eae8d7be5de46dc1c7933013cc277fd69255c07e7f38d6bc2831b58f
]
```

### **Log output**
Log dump of arana-alpha-1 with debug logs on can be viewed [here](https://gist.github.com/dutterbutter/7939719c9a79f30844359c7236aad517). 

Log dump of arana-alpha-3 with debug logs off can be viewed [here](https://gist.github.com/dutterbutter/656710a64173ea1f293356809ca00707). 

### **Expected behaviour**

It should continue to progress through keygen every session, and in these network params that should be every 150 blocks. 

### **Environment**
- **Chainspecs**: [Arana alpha chainspecs](https://github.com/webb-tools/dkg-substrate/blob/db/arana-alpha-2/chainspecs/arana-alpha-plain.json) 
- **Machine storage**: 73M of 119G   1% /mnt/blockstorage
- **Cloud provider**: Instance is running on Vultr  
- **Branch/commit**: [arana-alpha-1](https://github.com/webb-tools/dkg-substrate/tree/db/arana-alpha-2)

**Machine specs:**
- **vCPU/s:** 2 vCPUs
- **RAM:** 8192 MB
- **Storage:** 50 GB NVMe + 128GB of Block Storage
- **Bandwidth:** .28 GB of 5000 GB

**Note:** The standalone network uses the integration tests parameters which can be found [here](https://github.com/webb-tools/dkg-substrate/blob/f69a336cf20c89d04db4f2110851f12d3e325a97/standalone/runtime/src/lib.rs#L291).

### Reproduce Locally

1. `git checkout db/arana-alpha-2`
2. `cargo build --release -p dkg-standalone-node --features integration-tests`
3. `sh keys.sh` - this will generate keys for each node in `/tmp/blockstorage/standalone-n`
4. Start node: 

**Terminal 1:**
```
./target/release/dkg-standalone-node \
  --chain ./chainspecs/arana-alpha-raw.json \
  --base-path /tmp/blockstorage/standalone-1 --port 30334 \
  --validator \
  --ws-port 9944 --ws-external --rpc-port 9980 \
  --rpc-cors all --rpc-external \
  --unsafe-ws-external --unsafe-rpc-external \
  --rpc-methods=unsafe
```

**Terminal 2:**
```
./target/release/dkg-standalone-node \
  --chain ./chainspecs/arana-alpha-raw.json \
  --base-path /tmp/blockstorage/standalone-2 --port 30335 \
  --validator \
  --ws-port 9945 --ws-external --rpc-port 9981 \
  --rpc-cors all --rpc-external \
  --unsafe-ws-external --unsafe-rpc-external \
  --rpc-methods=unsafe
```

**Terminal 3:**
```
./target/release/dkg-standalone-node \
  --chain ./chainspecs/arana-alpha-raw.json \
  --base-path /tmp/blockstorage/standalone-3 --port 30336 \
  --validator \
  --ws-port 9946 --ws-external --rpc-port 9982 \
  --rpc-cors all --rpc-external \
  --unsafe-ws-external --unsafe-rpc-external \
  --rpc-methods=unsafe
``` 

**Note:** Make sure filepaths are correct

**Comment by nepoche** [comment]
Logs starting from the beginning of the chain, up until the misbehavior report:

https://gist.github.com/nepoche/50fd8a01eb79c5941d0abf71a85173d9
