### ISSUE TITLE
Mac M1 cargo build issue: error: linking with `cc` failed: exit status: 1 (Mac m1)

### ISSUE THREAD

**Issue by herou** [webb-tools/dkg-substrate#449]
Not able to build a project because of this issue:
`error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/var/folders/5w/j2mkxftx2xz55c696xp23gzh0000gn/T/rustciwy51y/symbols.o" "/Users/elioprifti/dkg-substrate/target/debug/deps/dkg_standalone_node-3e72bef5f25657ad.10sw7xj1rkq1p2nk.rcgu.o" "/Users/elioprifti/dkg-substrate/target/debug/deps/dkg_standalone_node-3e72bef5f25657ad.10ut9rvejkcsmvr1.rcgu.o" "/Users/elioprifti/dkg-substrate/target/debug/deps/dkg_standalone_node-3e72bef5f25657ad.112iyrdupdm8w5vw.rcgu.o" "/Users/elioprifti/dkg-substrate/target/debug/deps/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-d0e3d0b2f5dc30fb.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-12083e42f9a7d1fc.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-def158ba03cb504e.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-e83dd9bd71bd52bd.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-a149d8756e403a5c.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-95a7e52c78a3fba1.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-dd6de681850a671c.rlib" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-ec608688b97371b8.rlib" "-lgmp" "-framework" "Security" "-framework" "Security" "-lc++" "-framework" "SystemConfiguration" "-framework" "Security" "-framework" "CoreFoundation" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/elioprifti/.rustup/toolchains/nightly-2022-05-15-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/elioprifti/dkg-substrate/target/debug/deps/dkg_standalone_node-3e72bef5f25657ad" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: library not found for -lgmp
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `dkg-standalone-node` due to previous error
warning: build failed, waiting for other jobs to finish...
elioprifti@pc-193-62 dkg-substrate % `

I can build other projects but not this one. Any idea?

Already reported this but not solution so far: https://substrate.stackexchange.com/questions/6058/error-linking-with-cc-failed-exit-status-1-mac-m1?noredirect=1#comment5956_6058

**Comment by dutterbutter** [comment]
@herou have you followed our section on [troubleshooting](https://github.com/webb-tools/dkg-substrate#troubleshooting-for-apple-silicon-users) Apple silicon? 

I would first ensure your Homebrew is installed in the correct directory, and that `gmp` is installed. Depending on your setup you may need to set the following flags in your bash profile or whatever you use (e.g. zshrc).

```
export PATH=$HOME/bin:/opt/homebrew/bin:$PATH
export LDFLAGS=-L/opt/homebrew/opt/llvm/lib
export CPPFLAGS=-I/opt/homebrew/opt/llvm/include
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar
export RUSTFLAGS='-L /opt/homebrew/lib'
```

Make sure to `source ~/.bash_profile`

**Comment by herou** [comment]
@dutterbutter 
`elioprifti@Elios-MacBook-Air ~ % brew help
Example usage:
  brew search TEXT|/REGEX/
  brew info [FORMULA|CASK...]
  brew install FORMULA|CASK...
  brew update
  brew upgrade [FORMULA|CASK...]
  brew uninstall FORMULA|CASK...
  brew list [FORMULA|CASK...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA|CASK

Contributing:
  brew create URL [--no-fetch]
  brew edit [FORMULA|CASK...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
elioprifti@Elios-MacBook-Air ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R elioprifti:admin /opt/homebrew
==> Downloading and installing Homebrew...
HEAD is now at 4abca3fa1 Merge pull request #14169 from Homebrew/dependabot/bundler/Library/Homebrew/rack-3.0.1
Updated 2 taps (homebrew/core and homebrew/cask).
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

elioprifti@Elios-MacBook-Air ~ % brew update
Already up-to-date.
elioprifti@Elios-MacBook-Air ~ % brew install openssl
Warning: openssl@3 3.0.7 is already installed and up-to-date.
To reinstall 3.0.7, run:
  brew reinstall openssl@3
elioprifti@Elios-MacBook-Air ~ % echo 'export PATH=/opt/homebrew/bin:$PATH' >> ~/.bash_profile
elioprifti@Elios-MacBook-Air ~ % echo 'export RUSTFLAGS="-L /opt/homebrew/lib"' >> ~/.bash_profile
elioprifti@Elios-MacBook-Air ~ % brew install gmp
Warning: gmp 6.2.1_1 is already installed and up-to-date.
To reinstall 6.2.1_1, run:
  brew reinstall gmp`
  Thank you for your update. Above are all the commands executed from the troubleshooting section. Can you please take a look and tell me if you see something? Thank you!

**Comment by dutterbutter** [comment]
A couple things to check:

- Make sure `gmp` and `llvm` are installed in `/opt/homebrew/opt/`
- Make sure you do not have two versions of homebrew installed on your machine (the default for older macs was `/usr/local/bin`, make sure its not there) 
- Check your bash profile (whichever you use), has the above mentioned flags in the correct path 

The issue is most likely with your paths. Please ensure they are correct. Can you compile other Substrate based chains or is it just dkg-substrate?

**Comment by herou** [comment]
`Gmp` and `llvm` are installed in `/opt/homebrew/opt/`
<img width="557" alt="Screenshot 2022-11-23 at 23 49 35" src="https://user-images.githubusercontent.com/13895430/203659051-22febfcf-5a5a-4a42-b2c4-6f8dc3947dc0.png">

homebrew is NOT installed in` /usr/local/bin`
<img width="557" alt="Screenshot 2022-11-23 at 23 50 28" src="https://user-images.githubusercontent.com/13895430/203659157-41510814-49ee-4127-9bf4-25f55bf853cb.png">

My bashk profile
<img width="679" alt="Screenshot 2022-11-23 at 23 51 15" src="https://user-images.githubusercontent.com/13895430/203659237-c5837944-09a6-4f3d-8583-423ccaf5e5b9.png">

Yes, only dkg-substrate project can't compile!

**Comment by dutterbutter** [comment]
Please add the following lines to bash profile: 

```
export LDFLAGS=-L/opt/homebrew/opt/llvm/lib
export CPPFLAGS=-I/opt/homebrew/opt/llvm/include
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar
```

**Comment by herou** [comment]
Final .bash_profile looks like this but still having the same issue :/

`export PATH=/opt/homebrew/bin:$PATH
export RUSTFLAGS="-L /opt/homebrew/lib"
. "$HOME/.cargo/env"
export LDFLAGS=-L/opt/homebrew/opt/llvm/lib
export CPPFLAGS=-I/opt/homebrew/opt/llvm/include
export CC=/opt/homebrew/opt/llvm/bin/clang
export AR=/opt/homebrew/opt/llvm/bin/llvm-ar`

**Comment by dutterbutter** [comment]
@herou did you source your profile after updating?

**Comment by herou** [comment]
> source ~/.bash_profile

@dutterbutter Yes, of course!

**Comment by dutterbutter** [comment]
@shekohex any ideas here? I cannot reproduce on my side.

**Comment by shekohex** [comment]
Could you try `cargo clean` and then `cargo b -r -p dkg-standalone-node` again?

**Comment by herou** [comment]
@shekohex it worked. Thanks a lot :)
