### ISSUE TITLE
Not able to start dkg as bootnode

### ISSUE THREAD

**Issue by herou** [webb-tools/dkg-substrate#451]
**Describe the bug**

I was able to successfully setup my local env. 

**To Reproduce**
1. Open terminal and execute: `RUST_LOG=dkg=trace ./target/release/dkg-standalone-node --tmp --alice` or `RUST_LOG=dkg=trace ./target/release/dkg-standalone-node --tmp --bob` or `RUST_LOG=dkg=trace ./target/release/dkg-standalone-node --tmp --charlie`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```elioprifti@pc-193-62 dkg-substrate % RUST_LOG=dkg=trace ./target/release/dkg-standalone-node --tmp --alice
2022-11-24 20:29:08.910  INFO main sc_cli::runner: DKG Substrate Node    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: ✌️  version 3.0.0-45f135e12d2    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: ❤️  by Webb tools, 2017-2022    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: 📋 Chain specification: Local Testnet    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: 🏷  Node name: Alice    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: 👤 Role: AUTHORITY    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: 💾 Database: RocksDb at /var/folders/5w/j2mkxftx2xz55c696xp23gzh0000gn/T/substrateTFlrhP/chains/local_testnet/db/full    
2022-11-24 20:29:08.910  INFO main sc_cli::runner: ⛓  Native runtime: dkg-standalone-node-19 (dkg-standalone-node-0.tx1.au1)    

====================

Version: 3.0.0-45f135e12d2

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:702:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:586:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/sys_common/backtrace.rs:138:18
   6: rust_begin_unwind
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:584:5
   7: core::panicking::panic_fmt
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/panicking.rs:142:14
   8: <pallet_dkg_metadata::pallet::GenesisConfig<T> as frame_support::traits::hooks::GenesisBuild<T>>::build
   9: std::thread::local::LocalKey<T>::with
  10: sp_state_machine::basic::BasicExternalities::execute_with_storage
  11: <dkg_standalone_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  12: sp_runtime::BuildStorage::build_storage
  13: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
  14: sc_service::client::client::Client<B,E,Block,RA>::new
  15: sc_service::builder::new_full_parts
  16: dkg_standalone_node::service::new_partial
  17: dkg_standalone_node::service::new_full
  18: std::thread::local::LocalKey<T>::with
  19: tokio::park::thread::CachedParkThread::block_on
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  21: tokio::runtime::Runtime::block_on
  22: sc_cli::runner::Runner<C>::run_node_until_exit
  23: dkg_standalone_node::command::run
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::rt::lang_start::{{closure}}
  26: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/70b3681bf621bc0de91ffab711b2350068b4c466/library/std/src/rt.rs:128:20
  27: _main


Thread 'main' panicked at 'Not enough authority ids specified', /Users/elioprifti/dkg-substrate/pallets/dkg-metadata/src/lib.rs:608

This is a bug. Please report it at:

        support.anonymous.an

elioprifti@pc-193-62 dkg-substrate % 
...
  ```
</details> 

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Rust version(e.g. `rustc 1.65.0 (897e37553 2022-11-02)`)
 - Master

**Other information and links**

**Comment by herou** [comment]
@dutterbutter Can you please take a look? Thank you!

**Comment by drewstone** [comment]
Your keygen threshold is too large for # of authorities you're using. You'll need to update that in the chainspec. Plesae refer to the error in your logs as it very clearly states what line it fails at and why. 
```
self.authority_ids.len() >= self.keygen_threshold
```

**Comment by shekohex** [comment]
in the standalone chainspec the Initial PoA authorities are only three as you can see here

https://github.com/webb-tools/dkg-substrate/blob/45f135e12d214d7e6680c666c959627d1bf6d9aa/standalone/node/src/chain_spec.rs#L174-L181

> Notice that Dave and Eve are commented out.

but the `keygen_threshold ` is `5` which requires `5` authorities to start with
https://github.com/webb-tools/dkg-substrate/blob/45f135e12d214d7e6680c666c959627d1bf6d9aa/standalone/node/src/chain_spec.rs#L371-L372

Either decrease this to say 3, and the `signature_threshold` to say `1`; or add more authorities.

Other way without modifying anything is to instead of using the chainspec of the localtest (which is the default) you could switch to the `dev` chainspec (which already includes 5 authorities), by adding `--dev` or `--chain dev` to your startup flags. 

> Note that you will need to run the # of authorities you added, that or the DKG will not be able to generate or start the Keygen protocol.

**Comment by herou** [comment]
> in the standalone chainspec the Initial PoA authorities are only three as you can see here
> 
> https://github.com/webb-tools/dkg-substrate/blob/45f135e12d214d7e6680c666c959627d1bf6d9aa/standalone/node/src/chain_spec.rs#L174-L181
> 
> > Notice that Dave and Eve are commented out.
> 
> but the `keygen_threshold ` is `5` which requires `5` authorities to start with
> 
> https://github.com/webb-tools/dkg-substrate/blob/45f135e12d214d7e6680c666c959627d1bf6d9aa/standalone/node/src/chain_spec.rs#L371-L372
> 
> Either decrease this to say 3, and the `signature_threshold` to say `1`; or add more authorities.
> 
> Other way without modifying anything is to instead of using the chainspec of the localtest (which is the default) you could switch to the `dev` chainspec (which already includes 5 authorities), by adding `--dev` or `--chain dev` to your startup flags.
> 
> > Note that you will need to run the # of authorities you added, that or the DKG will not be able to generate or start the Keygen protocol.

@shekohex You are awesome!

**Comment by herou** [comment]
I did close this issue. Should I create a PR for this?
