### ISSUE TITLE
[TASK] Ensure all unwrap is removed and add check to CI

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#572]
**Task summary**
Remove all unwrap() in pallet code, add `[deny(clippy::unwrap_used)]` to lint check CI so that we catch any regression

https://github.com/webb-tools/dkg-substrate/pull/569

**Comment by Nutomic** [comment]
You can copy the changes I made in relayer for this, it also includes some other potential crashes such as accessing a Vec with `[]` operator.

https://github.com/webb-tools/relayer/pull/408
