### ISSUE TITLE
[TASK] Cargo Makefile Support

### ISSUE THREAD

**Issue by tbraun96** [webb-tools/dkg-substrate#588]
Now that we have many possible commands that can be used in this repo, using a workspace-level Cargo Makefile would help simplify interaction with the codebase. E.g., instead of `cargo build --release -p dkg-standalone-node --features=integration-tests,testing`, we can use `cargo make build-test`. Instead of `cargo run --package dkg-test-orchestrator --features=debug-tracing -- --config ./dkg-test-orchestrator/config/t3n2.toml --tmp ./tmp`, we can use `cargo make test-t3n2` and so on.

**Comment by shekohex** [comment]
[justfile](https://github.com/casey/just) also sounds good too

**Comment by dutterbutter** [comment]
Additional tasks in this scope:

- [ ] Update `README.md` with relevant make commands
- [ ] Include relevant make commands in the Tangle node operator section
