### ISSUE TITLE
[TASK] ProposalSetUpdate and RefreshVote proposals should never expire

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#609]
**Task summary**
Currently all proposals have an expiry limit, but it would be better if we can assign that depending on the type of proposal, certain types namely `ProposalSetUpdate` and `RefreshVote` is necessary for keygen process to complete and session to rotate, these should never expire and should be signed.

**Comment by tbraun96** [comment]
Yes, agreed.
