### ISSUE TITLE
[SPEC] Investigate best line of action if key refresh fails

### ISSUE THREAD

**Issue by Wizdave97** [webb-tools/dkg-substrate#61]
If next public key signature is not found on chain at session change, Some availabe options that would ensure the protocol keeps running is to

1. Retain current authorities and current public key and do not signal an authority set change.
    This way we can ensure the dkg system can still sign proposals.
    Slashing the incoming set whose key was not found onchain
2. Have a set of emergency DKG authorities that have an emergency publickey and signature on chain and rotate the 
    authorities to that instead.

**Comment by dutterbutter** [comment]
#121
