### ISSUE TITLE
[TASK] Improve the emitted events information

### ISSUE THREAD

**Issue by shekohex** [webb-tools/dkg-substrate#621]
**Task summary**

It is not clear in the emitted events what `chain_id` refers to, is it the src chain or the target chain?
Example 1:
![image](https://github.com/webb-tools/dkg-substrate/assets/14620076/26eed939-5c45-4232-b523-497f47bbe8c8)
Example 2:
![image](https://github.com/webb-tools/dkg-substrate/assets/14620076/4a681564-6032-4298-9564-166792be5f30)
Example 3:
![image](https://github.com/webb-tools/dkg-substrate/assets/14620076/83abfbf9-e010-42fa-8316-dd87c5f18186)
A good example:
![image](https://github.com/webb-tools/dkg-substrate/assets/14620076/54bef746-1d4d-4d11-8369-78fb8c7bbd81)

**Specification reference**

- Clearly the `chain_id` in question is the `src_chain_id` so we should rename that to make it clear.

**Other information and links**

**Comment by 1xstj** [comment]
Done by https://github.com/webb-tools/dkg-substrate/commit/efb068bef2e46843688d9ba50773517dcbfb422a right?
