### ISSUE TITLE
[TASK] Prioritise certain types of proposals to sign

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#637]
**Task summary**
If we have a large backlog of unsigned proposals in unsigned proposals queue, some operational proposals like `RefreshVote` and `ProposerSetUpdate` might get delayed to be picked for signing.

Prioritise certain types of proposals and pick for signing overriding the default check of "oldest proposal". The proposals with higher priority
- RefreshVote
- ProposerSetUpdate

**Comment by shekohex** [comment]
Maybe we could derive `Ord` and `PartialOrd` for the Proposal enum, where we order them by the type here making the `RefreshVote` is the largest thing, then `ProposerSetUpdate` then the rest are all equal. this way, when we insert we can always (while modifying) sort them.

**Comment by 1xstj** [comment]
After a closer look, this task is no longer necessary, after https://github.com/webb-tools/dkg-substrate/pull/601, we dont have any limits on the number of proposals picked for signing. This combined with https://github.com/webb-tools/dkg-substrate/pull/611 will ensure that the Refresh/ProposerSet update proposals will always be picked for signing
