### ISSUE TITLE
[TASK] Reduce function args to acknowledge proposal/reject proposal

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#647]
**Task summary**
Currently acknowlege/reject proposal takes 
`			nonce: ProposalNonce,
			src_chain_id: TypedChainId,
			r_id: ResourceId,
` as arguments, remove this requirement and read the data from the given proposal
https://github.com/webb-tools/dkg-substrate/blob/73238220f282ebd2015543464c6db1fb15d970c5/pallets/dkg-proposals/src/lib.rs#L535

**Comment by drewstone** [comment]
This will require a companion PRs on the relayer / webb-rs too, would be great to handle that together too @1xstj (changing the args to the acknowledge prop handler).

Please also don't forget to update the types after changes like these on this repo.
