### ISSUE TITLE
[BUG] Standalone node polkadotjs apps UI types issue

### ISSUE THREAD

**Issue by nepoche** [webb-tools/dkg-substrate#66]
### Overview

This issue was found while working on a testnet deployment on branch `nathan/dkg-testnet`.

3 Validator nodes were spun up and are able to communicate and produce blocks at endpoints:
- `wss://testnet1.webb.tools`
- `wss://testnet2.webb.tools`
- `wss://testnet3.webb.tools`

### Observed Behavior

While attempting some queries on the dkg pallet through the apps UI, the UI will hit an error. The below error is shown when attempting to select the `dkgPublicKey()` option under dkg pallet for chain state queries:

![Screen Shot 2022-01-10 at 9 28 27 AM](https://user-images.githubusercontent.com/16654909/148782698-a3b75100-8589-4d85-ad22-0a116b05cf1a.png)

Note: some chain state queries such as authorities() work as expected, but the above `dkgPublicKey()` errors.

### Expected Behavior

The DKG public key should be queried and presented on the apps UI.

**Comment by drewstone** [comment]
Being tracked now here: https://github.com/polkadot-js/apps/issues/6840

**Comment by nepoche** [comment]
Looks like it was fixed - but now chainstate queries for dkg related things are not returning proper values:

![Screen Shot 2022-01-19 at 11 35 41 AM](https://user-images.githubusercontent.com/16654909/150163468-d34c987e-cd5b-4737-b107-ba2b73ed4744.png)

**Comment by drewstone** [comment]
Has the keygen succeeded? We should restart testnet too to be sure.
