### ISSUE TITLE
[BUG] Sign / keygen cache does not work

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#74]
## Description
Persistent DKG key material doesn't work as expected when using 3-node testnet with `--tmp` DBs (and likely when nodes are separated, which is untested). We should identify how to test this more deeply and decide on the expected behavior.

## Steps to reproduce
1. Run the 3 node testnet, finish keygen.
2. Shut off a node and wait.
3. Turn the node back on.
4. Initiate anchor proposal sign script, proposal succeeds but never gets signed.

**Comment by shekohex** [comment]
running the node with a `--tmp` means it will delete the database on shutdown. try running them with `-d /tmp/{alice,bob,charlie}`  instead and try again.

**Comment by dutterbutter** [comment]
@drewstone can you please add more context to reproduce.
