### ISSUE TITLE
[TASK] Improve logging of the DKG

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#83]
# Overview
We should have better logging of keygen and signing for testing purposes and readability about different actions taking place. Some of these are:
- Seeing the active group public key generated from `keygen` of current authorities
- Seeing the next group public key generated from `keygen` of next authorities
- Seeing the refresh process in action.
- [ ] #89

Ideally we have this possible on a separate logging target so that the large DKG message spam doesn't get shown.

**Comment by dutterbutter** [comment]
Closing in favour of #89
